FROM node:alpine
# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json /usr/src/app/

COPY package*.json ./
COPY prisma ./prisma/
RUN yarn install
RUN npx prisma generate
# Bundle app source
COPY . /usr/src/app
RUN yarn run build



EXPOSE 3000
CMD [ "yarn", "start" ]